name: raw2zarr-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - mamba
  - cartopy
  - fsspec
  - jupyterlab
  - notebook
  - ipykernel
  - dask
  - netcdf4
  - bottleneck
  - zarr>=3.0.8
  - ca-certificates
  - certifi
  - openssl
  - s3fs>=2025.5.1
  - wradlib
  - hvplot
  - datashader
  - xarray>=2025.07.1
  - xradar>=0.10.0
  - pytest
  - pytest-cov
  - pytest-doctestplus
  - pytest-sugar
  - pytest-xdist
  - nbmake
  - pydantic
  - icechunk>=1.0.0
  - pandas
  - numpy
  - icechunk
  - pandas
  - pip
  - pip:
      - .
