name: raw2zarr
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - mamba
  - fsspec
  - jupyterlab
  - notebook
  - ipykernel
  - dask
  - netcdf4
  - bottleneck
  - zarr>=3.1.0
  - ca-certificates
  - certifi
  - openssl
  - s3fs>=2025.5.1
  - xarray>=2025.07.1
  - xradar>=0.10.0
  - pytest
  - pytest-cov
  - pytest-doctestplus
  - pytest-sugar
  - pytest-xdist
  - nbmake
  - pydantic
  - icechunk>=1.0.3
  - arraylake>=0.1.1
  - pandas
  - numpy
  - icechunk
  - pandas
  - pip
  - pip:
      - git+https://github.com/aladinor/raw2zarr.git
