name: raw2zarr
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - mamba
  - cartopy
  - fsspec
  - jupyterlab
  - dask
  - netcdf4
  - bottleneck
  - zarr
  - ca-certificates
  - certifi
  - openssl
  - s3fs>=2024.3.1
  - arm_pyart>=1.18.1
  - wradlib
  - hvplot
  - datashader
  - xarray>=2024.10
  - xradar>=0.8.0
  - pip
  - pip:
      - -e .
