name: raw2zarr
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11
  - mamba
  - fsspec
  - jupyterlab
  - notebook
  - ipykernel
  - dask
  - netcdf4
  - bottleneck
  - coiled
  - hvplot
  - datashader
  - zarr>=3.1.2
  - ca-certificates
  - certifi
  - openssl
  - s3fs>=2025.5.1
  - xarray>=2025.10.0
  - xradar>=0.10.0
  - pytest
  - pytest-cov
  - pytest-doctestplus
  - pytest-sugar
  - pytest-xdist
  - nbmake
  - pydantic
  - pandas
  - numpy<2.3
  - cmweather
  - pandas
  - pip
  - pip:
      - icechunk
      - arraylake
