name: raw2zarr
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - mamba
  - cartopy
  - fsspec
  - jupyterlab
  - dask
  - netcdf4
  - bottleneck
  - zarr
  - ca-certificates
  - certifi
  - openssl
  - s3fs>=2024.3.1
  - arm_pyart>=1.18.1
  - wradlib
  - hvplot
  - datashader
  - pip
  - pydata-sphinx-theme
  - pip:
      - git+https://github.com/aladinor/raw2zarr
      - git+https://github.com/openradar/xradar.git
      - git+https://github.com/pydata/xarray.git
