[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sigmet2zarr"
description = "Package for convertir Sigmet radar files into zarr format"
version = "2024.0.0.1"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
include = ['sigmet2zarr']
exclude = ["data", "notebooks" ]
